# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'iHackerNews' do
  pod 'AFNetworking', '~> 2.5'
  pod 'Facebook-iOS-SDK', '~> 4.1'
  pod 'QBImagePickerController', '~> 3.2'
  pod 'ChameleonFramework'
  pod 'DKCircleButton', '~> 1.1'
  pod 'PBFlatUI', '~> 1.1.0'
  pod 'SCLAlertView-Objective-C', '~> 0.7'
  pod 'libHN'
  pod 'MGSwipeTableCell', '~> 1.4'
  pod 'NSAttributedString+CCLFormat'
  pod 'DGActivityIndicatorView'
end

target 'iHackerNewsTests' do

end

