# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'iHackerNews' do
  pod 'AFNetworking', '~> 2.5'
  pod 'FBSDKLoginKit', '~> 4.7'
  pod 'FBSDKShareKit', '~> 4.8'
  pod 'QBImagePickerController', '~> 3.2'
  pod 'ChameleonFramework'
  pod 'DKCircleButton', '~> 1.1'
  pod 'PBFlatUI', '~> 1.1.0'
  pod 'SCLAlertView-Objective-C', '~> 0.7'
  pod 'libHN'
  pod 'MGSwipeTableCell', '~> 1.4'
  pod 'NSAttributedString+CCLFormat'
  pod 'DGActivityIndicatorView'
  pod 'RESideMenu', '~> 4.0.7'
  pod 'JFMinimalNotifications', '~> 0.0.4'
  pod 'UzysCircularProgressPullToRefresh', '~> 1.1'
  pod 'BubbleTransition-objc', '~> 0.1'
  pod 'MRProgress', '~> 0.8'
  pod 'JVFloatLabeledTextField'
  pod 'MNFloatingActionButton', '~> 0.1'
end

target 'iHackerNewsTests' do

end

